// needs a closure

// https://github.com/codecomputerlove/PhotoSwipe
// http://www.photoswipe.com/

var data = {
    allowUserZoom : true,
    autoStartSlideshow : false,
    allowRotationOnUserZoom : false,
    backButtonHideEnabled : true,
    captionAndToolbarAutoHideDelay : 5000,
    captionAndToolbarFlipPosition : false,
    captionAndToolbarHide : false,
    captionAndToolbarOpacity : 0.8,
    captionAndToolbarShowEmptyCaptions : true,
    cacheMode : Code.PhotoSwipe.Cache.Mode.normal,
    doubleTapSpeed : 300,
    doubleTapZoomLevel : 2.5,
    enableDrag : true,
    enableKeyboard : true,
    enableMouseWheel : true,
    fadeInSpeed : 250,
    fadeOutSpeed : 250,
    imageScaleMethod : 'fit',
    invertMouseWheel : false,
    jQueryMobileDialogHash : '&ui-state=dialog',
    loop : true,
    margin : 20,
    maxUserZoom : 5.0,
    minUserZoom : 0.5,
    mouseWheelSpeed : 500,
    nextPreviousSlideSpeed : 0,
    preventHide : false,
    preventSlideshow : false,
    slideshowDelay : 3000,
    slideSpeed : 250,
    swipeThreshold : 50,
    swipeTimeThreshold : 250,
    slideTimingFunction : 'ease-out',
    zIndex : 1000
};

var types = {
    allowUserZoom : 'bool',
    autoStartSlideshow : 'bool',
    allowRotationOnUserZoom : 'bool',
    backButtonHideEnabled : 'bool',
    captionAndToolbarAutoHideDelay : 'int',
    captionAndToolbarFlipPosition : 'bool',
    captionAndToolbarHide : 'bool',
    captionAndToolbarOpacity : 'int',
    captionAndToolbarShowEmptyCaptions : 'bool',
    cacheMode : Code.PhotoSwipe.Cache.Mode.normal,
    doubleTapSpeed : 'int',
    doubleTapZoomLevel : 'int',
    enableDrag : 'bool',
    enableKeyboard : 'bool',
    enableMouseWheel : 'bool',
    fadeInSpeed : 'int',
    fadeOutSpeed : 'int',
    imageScaleMethod : 'fit',
    invertMouseWheel : 'bool',
    jQueryMobileDialogHash : '&ui-state=dialog',
    loop : 'bool',
    margin : 'int',
    maxUserZoom : 'int',
    minUserZoom : 'int',
    mouseWheelSpeed : 'int',
    nextPreviousSlideSpeed : 'int',
    preventHide : 'bool',
    preventSlideshow : 'bool',
    slideshowDelay : 'int',
    slideSpeed : 'int',
    swipeThreshold : 'int',
    swipeTimeThreshold : 'int',
    slideTimingFunction : 'ease-out',
    zIndex : 'int'
};